### ISSUE TITLE
BUG: LocalCollection._search_distance_matrix() "Payload and ids_inv must be the same size"

### ISSUE THREAD

**Issue by benste** [qdrant/qdrant-client#809] opened 2024-10-11 11:11 UTC
https://github.com/qdrant/qdrant-client/blob/4a2c0abce572a107ef0fce3930aac76b5ea02c7a/qdrant_client/local/local_collection.py#L1551

When calling search_matrix_pairs on a local client, the error "Payload and ids_inv must be the same size" is returned. 

I believe the linked line of code should read 
`search_vector = sampled.vector`

**Comment by joein** [comment] 2024-10-11 15:15
Hi @benste 

Could you please provide a minimal reproducible example?

**Comment by benste** [comment] 2024-10-11 15:41
Hey @joein 

Thanks for the quick reply. This is my first issue, so bare with me while I navigate how to be most informative.

**Minimal reproducible example**
```from uuid import uuid4

from qdrant_client import QdrantClient
from qdrant_client.models import (
    Distance,
    PointStruct,
    VectorParams,
)
import numpy as np

vector_db_client = QdrantClient(":memory:")
collection_name = "default"
vector_db_client.create_collection(
    collection_name=collection_name,
    vectors_config=VectorParams(size=512, distance=Distance.COSINE),
)

points = [
    PointStruct(
        id=str(uuid4()),
        vector=np.random.rand(512),
    )
    for _ in range(100)
]

vector_db_client.upsert(collection_name=collection_name, points=points)

pair_similarity = vector_db_client.search_matrix_pairs(
    collection_name=collection_name,
    sample=10,
    limit=2,
)
```


**traceback**
```---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 29
     19 points = [
     20     PointStruct(
     21         id=str(uuid4()),
   (...)
     24     for _ in range(100)
     25 ]
     27 vector_db_client.upsert(collection_name=collection_name, points=points)
---> 29 pair_similarity = vector_db_client.search_matrix_pairs(
     30     collection_name=collection_name,
     31     sample=10,
     32     limit=2,
     33     # query_filter=query_filter,
     34 )

File [~/.cache/pypoetry/virtualenvs/olympicsrag-2CGqyRo0-py3.10/lib/python3.10/site-packages/qdrant_client/qdrant_client.py:1009](http://localhost:8888/home/bens/.cache/pypoetry/virtualenvs/olympicsrag-2CGqyRo0-py3.10/lib/python3.10/site-packages/qdrant_client/qdrant_client.py#line=1008), in QdrantClient.search_matrix_pairs(self, collection_name, query_filter, limit, sample, using, consistency, timeout, shard_key_selector, **kwargs)
    986 """Compute distance matrix for sampled points with a pair-based output format.
    987 Args:
    988     collection_name: Name of the collection
   (...)
   1005     Return distance matrix using a pair-based encoding.
   1006 """
   1007 assert len(kwargs) == 0, f"Unknown arguments: {list(kwargs.keys())}"
-> 1009 return self._client.search_matrix_pairs(
   1010     collection_name=collection_name,
   1011     query_filter=query_filter,
   1012     limit=limit,
   1013     sample=sample,
   1014     using=using,
   1015     consistency=consistency,
   1016     timeout=timeout,
   1017     shard_key_selector=shard_key_selector,
   1018     **kwargs,
   1019 )

File [~/.cache/pypoetry/virtualenvs/olympicsrag-2CGqyRo0-py3.10/lib/python3.10/site-packages/qdrant_client/local/qdrant_local.py:238](http://localhost:8888/home/bens/.cache/pypoetry/virtualenvs/olympicsrag-2CGqyRo0-py3.10/lib/python3.10/site-packages/qdrant_client/local/qdrant_local.py#line=237), in QdrantLocal.search_matrix_pairs(self, collection_name, query_filter, limit, sample, using, **kwargs)
    228 def search_matrix_pairs(
    229     self,
    230     collection_name: str,
   (...)
    235     **kwargs: Any,
    236 ) -> types.SearchMatrixPairsResponse:
    237     collection = self._get_collection(collection_name)
--> 238     return collection.search_matrix_pairs(
    239         query_filter=query_filter, limit=limit, sample=sample, using=using
    240     )

File [~/.cache/pypoetry/virtualenvs/olympicsrag-2CGqyRo0-py3.10/lib/python3.10/site-packages/qdrant_client/local/local_collection.py:1499](http://localhost:8888/home/bens/.cache/pypoetry/virtualenvs/olympicsrag-2CGqyRo0-py3.10/lib/python3.10/site-packages/qdrant_client/local/local_collection.py#line=1498), in LocalCollection.search_matrix_pairs(self, query_filter, limit, sample, using)
   1492 def search_matrix_pairs(
   1493     self,
   1494     query_filter: Optional[types.Filter] = None,
   (...)
   1497     using: Optional[str] = None,
   1498 ) -> types.SearchMatrixPairsResponse:
-> 1499     ids, all_scores = self._search_distance_matrix(
   1500         query_filter=query_filter, limit=limit, sample=sample, using=using
   1501     )
   1502     pairs = []
   1503     for sample_id, sample_scores in list(zip(ids, all_scores)):

File [~/.cache/pypoetry/virtualenvs/olympicsrag-2CGqyRo0-py3.10/lib/python3.10/site-packages/qdrant_client/local/local_collection.py:1551](http://localhost:8888/home/bens/.cache/pypoetry/virtualenvs/olympicsrag-2CGqyRo0-py3.10/lib/python3.10/site-packages/qdrant_client/local/local_collection.py#line=1550), in LocalCollection._search_distance_matrix(self, query_filter, limit, sample, using)
   1549 ids_to_includes = [x for (i, x) in enumerate(ids) if i != sampled_id_index]
   1550 sampling_filter = _include_ids_in_filter(query_filter, ids_to_includes)
-> 1551 search_vector = sampled.vector[search_in_vector_name]
   1552 samples_scores = self.search(
   1553     query_vector=(search_in_vector_name, search_vector),
   1554     query_filter=sampling_filter,
   (...)
   1557     with_vectors=False,
   1558 )
   1559 scores.append(samples_scores)

TypeError: list indices must be integers or slices, not str```

**Comment by joein** [comment] 2024-10-11 15:43
@benste thank you for the example
I have fixed this one locally and will soon create a PR with it, however, this traceback is different from what you've desribed in the title (`Payload and ids_inv must be the same size`) - I haven't been able to get such an error yet

**Comment by benste** [comment] 2024-10-11 15:46
Interesting, I'm using qdrant-client 1.12.0 and python 3.10.13 on Linux, if that helps

**Comment by joein** [comment] 2024-10-11 15:59
This error "Payload and ids_inv must be the same size" actually occurs when you are upserting points
Maybe you had something specific during upsertion?

**Comment by joein** [comment] 2024-10-11 16:35
#810

**Comment by joein** [comment] 2024-10-18 13:29
closing if for now, since the original title is about upsertion, and the actual problem discussed has been fixed and will be available as of the next release

**Closed by joein** 2024-10-18 13:29 UTC
