### ISSUE TITLE
similarity search with threshold and grouping: no documentation available

### ISSUE THREAD

**Issue by sglebs** [qdrant/qdrant-client#384] opened 2023-11-26 01:33 UTC
The grouping API looks very interesting(https://qdrant.tech/documentation/concepts/search/#grouping-api) because it allows the fetching of the whole doc that has been chopped.

Unfortunately there are no examples documented with the python client on how to use similarity+threshold+grouping.

I use langchain and I see it calls async def asimilarity_search_with_score. I don't see how I can pass instructions to say which metadata field I want it to use for grouping. Does the client have smarts to switch to https://qdrant.tech/documentation/concepts/search/#grouping-api ? Will my filters + threshold still work?

I would love to be able to use grouping through langchain but I just can't figure it out looking at the python-client package.

**Comment by joein** [comment] 2023-11-26 17:15
Hello @sglebs 

I think that grouping functionality is not that spread among the other vector databases at the moment and langchain does not support it (at least I couldn't find any reference, but, unfortunately, I am not an expert in langchain).

you can check method's signature (`search_groups`), it does support filters and score threshold
a brief example of using `search_groups` can be found here https://qdrant.tech/documentation/concepts/search/#search-groups

**Comment by joein** [comment] 2023-12-10 21:59
Closing this issue, since the problem is that langchain does not currently support grouping functionality

**Closed by joein** 2023-12-10 21:59 UTC
