### ISSUE TITLE
[W:onnxruntime:Default, onnxruntime_pybind_state.cc:1827 CreateInferencePybindStateModule] Init provider bridge failed.

### ISSUE THREAD

**Issue by happysalada** [qdrant/qdrant-client#307] opened 2023-09-19 15:19 UTC
testing with qdrant-client 1.5.4 and fastembed 0.0.4
the following code on linux-x86_64
```
from qdrant_client import QdrantClient

client = QdrantClient(host="localhost", port=6333)

documents = [ "executed by the signatures of their respective authorized representatives.  The Parties signatures below acknowledge understanding and acceptance of project objectives, scope, deliverables, resources and fees.  The BUYER Project Sponsor will be responsible for generating the purchase order once all parties below have signed this document.", "something else"
]

metadata = [ {"deliverables": "something"}, {"deliverables": "something else"}]

ids = [1, 2]

client.add(
    collection_name="agora_anonymised_db",
    documents=documents,
    metadata=metadata,
    ids=ids
)
```
gives me the error in the issue title.

**Comment by NirantK** [comment] 2023-09-19 15:25
This seems like an ONNX configuration error: https://github.com/microsoft/onnxruntime/issues/13499

Also, can you reproduce the error with qdrant-client 1.5.1 by any chance?

**Comment by NirantK** [comment] 2023-09-19 15:39
Tried to reproduce this here: https://colab.research.google.com/drive/1GUra8Bx1clgr4IJSqEQ59P3bMr65XA6T?usp=sharing

Unable to do so right now. Perhaps use a directory path which does not have Unicode characters and share?

**Comment by happysalada** [comment] 2023-09-19 16:28
not coming from the directory I run it on `/home/yt/agora`

also I have a question with the embeddings. flag embeddings have a max of 512 tokens. Using qdrant-client, do I have to split the input into chunks of 512 tokens, or does the library do it for me ?

**Comment by happysalada** [comment] 2023-09-19 16:28
good to know it's coming from onnxruntime though, I'm going to make some experiments.

**Comment by NirantK** [comment] 2023-09-20 04:42
Going forward, the library will truncate i.e. we drop tokens after the first 512 tokens. That seems to be the recommended, and in my early testing — surprisingly good for retrieval. 

I'm closing this issue for now since we know it's an ONNX issue. Please do re-open it if you're able to reproduce this via fastembed. Would love to hear what was the root cause!

**Closed by NirantK** 2023-09-20 04:42 UTC
