### ISSUE TITLE
Broken Dependency with Qdrant-Client on Replit

### ISSUE THREAD

**Issue by NirantK** [qdrant/qdrant-client#200] opened 2023-07-06 02:57 UTC
## How to reproduce
Go to Replit.new (while logged into your Replit account) 

```bash
poetry add qdrant-client
```

Results in this error: 
```python-stacktrace
poetry add qdrant-client
Using version ^1.3.1 for qdrant-client

Updating dependencies
Resolving dependencies... (3.8s)

  SolverProblemError

  Because no versions of replit match >3.2.4,<3.2.5 || >3.2.5,<3.2.6 || >3.2.6,<3.2.7 || >3.2.7,<3.2.8 || >3.2.8,<3.3.0 || >3.3.0,<4.0.0
   and replit (3.2.4) depends on typing_extensions (>=3.7.4,<4.0.0), replit (>=3.2.4,<3.2.5 || >3.2.5,<3.2.6 || >3.2.6,<3.2.7 || >3.2.7,<3.2.8 || >3.2.8,<3.3.0 || >3.3.0,<4.0.0) requires typing_extensions (>=3.7.4,<4.0.0).
  And because replit (3.2.6) depends on typing_extensions (>=3.7.4,<4.0.0), replit (>=3.2.4,<3.2.5 || >3.2.5,<3.2.7 || >3.2.7,<3.2.8 || >3.2.8,<3.3.0 || >3.3.0,<4.0.0) requires typing_extensions (>=3.7.4,<4.0.0).
  And because replit (3.2.7) depends on typing_extensions (>=3.7.4,<4.0.0)
   and replit (3.2.8) depends on typing_extensions (>=3.7.4,<4.0.0), replit (>=3.2.4,<3.2.5 || >3.2.5,<3.3.0 || >3.3.0,<4.0.0) requires typing_extensions (>=3.7.4,<4.0.0).
  And because replit (3.3.0) depends on typing_extensions (>=3.7.4,<4.0.0)
   and replit (3.2.5) depends on typing_extensions (>=3.7.4,<4.0.0), replit (>=3.2.4,<4.0.0) requires typing_extensions (>=3.7.4,<4.0.0).
  Because no versions of qdrant-client match >1.3.1,<2.0.0
   and qdrant-client (1.3.1) depends on typing-extensions (>=4.0.0,<4.6.0), qdrant-client (>=1.3.1,<2.0.0) requires typing-extensions (>=4.0.0,<4.6.0).
  Thus, qdrant-client (>=1.3.1,<2.0.0) is incompatible with replit (>=3.2.4,<4.0.0).
  So, because python-template depends on both replit (^3.2.4) and qdrant-client (^1.3.1), version solving failed.

  at venv/lib/python3.10/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
```

`pip install` side steps this error, by downgrading `typing-extensions` — but makes the environment confusing to use: 

```
WARNING: pip is using a content-addressable pool to install files from. This experimental feature is enabled through --use-feature=content-addressable-pool and it is not ready for production.
Installing collected packages: sniffio, exceptiongroup, h11, anyio, hyperframe, httpcore, hpack, typing-extensions, httpx, h2, grpcio, pydantic, portalocker, grpcio-tools, qdrant-client
  Attempting uninstall: typing-extensions
    Found existing installation: typing-extensions 3.10.0.2
    Uninstalling typing-extensions-3.10.0.2:
      Successfully uninstalled typing-extensions-3.10.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
replit 3.2.5 requires typing_extensions<4.0.0,>=3.7.4, but you have typing-extensions 4.5.0 which is incompatible.
```

## Possible Fixes

1. [*Preferred*] Both Replit and Qdrant Client upgrade to [latest](https://pypi.org/project/typing-extensions/#history) `typing-extensions` i.e. 4.7.1 
2. Replit upgrades to same version as Qdrant Client i.e. v4.5.0 for `typing-extentions`
3. [*Not Preferred*] Qdrant client downgrade to v4.0.0 for `typing-extentions`

**Comment by sfitts** [comment] 2023-07-07 15:58
The same kind of conflict exists between `qdrant-client` 1.3.1 and `pydantic-core` 2.1.2 (which requires `typing_extensions` of at least 4.6.0, but not 4.7.0).

**Comment by joein** [comment] 2023-07-08 06:27
Initial reason to have fixed dependency for `typing-extensions` was caused by their bug, as far as I remember it was version `4.6.0`.
 I will check how does it work with different versions of `typing-extensions`, and maybe update the dependencies

**Comment by joein** [comment] 2023-07-08 06:50
#175

**Comment by joein** [comment] 2023-07-08 07:00
It does not seem like `replit-py` is actively maintained https://github.com/replit/replit-py/issues/125
We probably would not downgrade our dependency, but I'll look into this

Issue with `pydantic` will be fixed

**Comment by joein** [comment] 2023-07-08 11:02
@sfitts 

Afaik `pydantic-core` is all about pydantic v2 ? 
At the moment pydantic v2 is not supported, it is not that easy as just allow a certain version of `typing-extensions` :(

However we are working on this. 
Should be available soon

**Comment by joein** [comment] 2023-07-08 11:57
#203

**Comment by sfitts** [comment] 2023-07-09 16:35
@joein Thanks for pointing that out -- we were not intending to use pydantic v2 at this point (it was getting dragged in by some sloppy requirements specification).  After cleaning that up we're now fine with `type_extensions` 4.5.0.  At least that's what pip-tools seems to think ;).

**Comment by joein** [comment] 2023-07-22 15:00
As of #214 qdrant-client supports pydantic v2 and typing-extensions are not explicitly frozen anymore, should be available with the next release

**Comment by joein** [comment] 2023-07-26 21:44
pydantic v2 support was introduced in `qdrant-client==1.3.2`

**Closed by joein** 2023-07-26 21:44 UTC
