### ISSUE TITLE
Timeouts when filtering and not using payload index

### ISSUE THREAD

**Issue by cirezd** [qdrant/qdrant-client#408] opened 2023-12-20 15:14 UTC
Hello, 

I have a collection with about 20k points and I use payload filters. Until recently, it worked without any issue. I did not set payload indices explicitly. After updating to 1.7., I experience many timeouts and I couldn't pinpoint the issue. Response times where 20-30 seconds (!), although in the qdrant logs it mentioned a few ms. After some trial and error, the issue lay in a missing payload index. I don't believe this is expected behaviour, considering the small collection size and it working in previous versions.

**Comment by generall** [comment] 2023-12-20 15:43
Why don't you just create a payload index?

**Comment by cirezd** [comment] 2023-12-20 15:53
Well, I did just that and I am posting here the solution to the issue I experienced. I wasted 2 hours debugging and I would have been happy to find more info on this. It is not obvious that you now need to create a payload index in order for qdrant to work

**Comment by generall** [comment] 2023-12-20 16:02
![image](https://github.com/qdrant/qdrant-client/assets/1935623/a9c94b06-d06e-4157-baa9-731feb545676)

https://qdrant.tech/documentation/quick-start/

**Comment by generall** [comment] 2023-12-20 16:06
@cirezd we are also working on the notification system, so that qdrant could tell you if some configs might be optimized. I hope it might improve the experience

**Comment by cirezd** [comment] 2023-12-20 16:08
> Well, I did just that and I am posting here the solution to the issue I experienced. I wasted 2 hours debugging and I would have been happy to find more info on this. It is not obvious that you **now** need to create a payload index in order for qdrant to work

There was a difference of 20-30 seconds vs. 100ms just by changing the version. I don't think see how linking getting started docs help here at all

**Comment by generall** [comment] 2023-12-20 16:29
I suspect that the timeout was mostly caused by restart rather than version upgrade. But thanks for your feedback anyway, we will definitely try to improve on this

**Comment by joein** [comment] 2024-01-04 10:38
I guess, the discussion has ended and the issue seems to be related to Qdrant itself, rather than qdrant-client.

I think I will close it for now, but feel free to re-open or transfer it to qdrant repo, if it has not yet been addressed

**Closed by joein** 2024-01-04 10:38 UTC
