### ISSUE TITLE
cache when deleting collection

### ISSUE THREAD

**Issue by EmanuelCampos** [qdrant/qdrant-client#406] opened 2023-12-18 17:09 UTC
I used qdrant-client and after deleting a few data, it still being retrieved. I didn't enable any cache and it just stopped retrieving after I deleted the docker container

**Comment by joein** [comment] 2024-01-06 13:55
Hi @EmanuelCampos 

Could you please provide more info on your collections?

`get_collection` output would be helpful

Also a minimum reproducible example would be really helpful

By the way, how do you delete your points? Did you use `.delete` method or `.delete_vectors`? Did you use `wait=False`?

**Comment by joein** [comment] 2024-01-19 00:37
I think that setting `wait=True` should solve your problem

@EmanuelCampos  Is it still actual, or I can close the issue?

**Comment by joein** [comment] 2024-01-30 18:54
Closing due to the lack of activity

**Closed by joein** 2024-01-30 18:54 UTC
